site_name: Funding
repo_url: https://github.com/systopia/funding
site_description: 'A guide for the Funding extension.'
site_author: 'systopia'
theme:
  name: material

nav:
  - 'Introduction': index.md
  - 'Naming conventions': naming-conventions.md
  - 'Administration':
    - 'Installation': administration/installation.md
    - 'Users and Permissions': administration/user-permissions.md
    - 'Necessary Adjustments': administration/necessary-adjustments.md

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite
  - toc:
      permalink: True
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark

plugins:
  - search:
      lang: en
